[package]
name = "oj-driver"
description = "workspaces, build options, metaprogram bootstrap and the link step for orangejuice"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
oj-codegen.workspace = true
oj-diag.workspace = true
oj-ir.workspace = true
oj-jit.workspace = true
oj-lexer.workspace = true
oj-link.workspace = true
oj-scope.workspace = true
oj-sema.workspace = true

[dev-dependencies]
oj-link.workspace = true
oj-testsupport.workspace = true
tempfile.workspace = true
