[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.3.2"
edition = "2024"
authors = ["Hanna Rose <me@hanna.lol>"]
license = "MIT"

[workspace.dependencies]
oj-codegen = { path = "crates/codegen" }
oj-diag = { path = "crates/diag" }
oj-driver = { path = "crates/driver" }
oj-ir = { path = "crates/ir" }
oj-jit = { path = "crates/jit" }
oj-lexer = { path = "crates/lexer" }
oj-meta = { path = "crates/meta" }
oj-link = { path = "crates/link" }
oj-runtime = { path = "crates/runtime" }
oj-scope = { path = "crates/scope" }
oj-sema = { path = "crates/sema" }
oj-source = { path = "crates/source" }
oj-syntax = { path = "crates/syntax" }
oj-testsupport = { path = "crates/testsupport" }
oj-types = { path = "crates/types" }

bitflags = "2"
mimalloc = { version = "0.1", default-features = false }
rustc-hash = "2"
boxcar = "0.2"
cc = "1"
indexmap = "2"
insta = "1"
libloading = "0.8"
memmap2 = "0.9"
tempfile = "3"
walkdir = "2"
