[package]
name = "oj-meta"
description = "the Compiler module ABI exposed to metaprograms by orangejuice"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rustc-hash.workspace = true

[dev-dependencies]
oj-diag.workspace = true
oj-lexer.workspace = true
oj-scope.workspace = true
oj-sema.workspace = true
oj-testsupport.workspace = true
tempfile.workspace = true
