[package]
name = "oj-cli"
description = "the oj command line interface"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "oj"
path = "src/main.rs"

[dependencies]
clap.workspace = true
oj-diag.workspace = true
oj-driver.workspace = true
oj-lexer.workspace = true
oj-scope.workspace = true
oj-sema.workspace = true
oj-source.workspace = true
oj-syntax.workspace = true

[dev-dependencies]
tempfile.workspace = true
