[package]
name = "oj-jit"
description = "ORC JIT compile-time execution for orangejuice"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
oj-codegen.workspace = true
oj-diag.workspace = true
oj-ir.workspace = true
oj-runtime.workspace = true
oj-scope.workspace = true
oj-sema.workspace = true
oj-syntax.workspace = true
oj-types.workspace = true
inkwell = { version = "0.10", default-features = false, features = ["llvm19-1", "target-x86"] }
llvm-sys = "191"
libloading.workspace = true
