[package]
name = "oj-scope"
description = "scope trees, declarations and name lookup for orangejuice"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
boxcar.workspace = true
oj-diag.workspace = true
oj-lexer.workspace = true
oj-source.workspace = true
oj-syntax.workspace = true

[dev-dependencies]
insta.workspace = true
oj-testsupport.workspace = true
tempfile.workspace = true
walkdir.workspace = true
