[package]
name = "oj-sema"
description = "the Jai typechecker and work-item scheduler for orangejuice"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
indexmap.workspace = true
rustc-hash.workspace = true
oj-diag.workspace = true
oj-lexer.workspace = true
oj-meta.workspace = true
oj-scope.workspace = true
oj-syntax.workspace = true
oj-types.workspace = true

[dev-dependencies]
insta.workspace = true
oj-testsupport.workspace = true
tempfile.workspace = true
walkdir.workspace = true
