[package]
name = "oj-codegen"
description = "LLVM code generation for orangejuice"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
oj-ir.workspace = true
oj-types.workspace = true

inkwell = { version = "0.10", default-features = false, features = ["llvm19-1", "target-x86", "target-aarch64"] }

[dev-dependencies]
oj-diag.workspace = true
oj-lexer.workspace = true
oj-scope.workspace = true
oj-sema.workspace = true
oj-testsupport.workspace = true
tempfile.workspace = true
