[package]
name = "oj-syntax"
description = "the Jai AST and parser for orangejuice"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bitflags.workspace = true
oj-diag.workspace = true
oj-lexer.workspace = true

[dev-dependencies]
insta.workspace = true
oj-source.workspace = true
oj-testsupport.workspace = true
walkdir.workspace = true
